theme = "onedark"

[editor]
line-number = "absolute"
mouse = false
scrolloff = 10
cursorline = true
auto-format = true
completion-replace = true
bufferline = "always"

[editor.statusline]
left = ["mode", "spinner","file-name", "version-control", "diagnostics"]
center = []
right = ["selections", "position", "file-encoding", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = true


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'

[editor.auto-save]
focus-lost = true
